bytez.webui/Areas/Admin/Controllers/BrandModelController.cs
using bytez.business.Abstract;
using bytez.business.Dto.BrandModel;
using bytez.entity.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace bytez.webui.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    public class BrandModelController : Controller
    {
        readonly private IBrandModelService _brandModelService;

        public BrandModelController(IBrandModelService brandModelService)
        {
            _brandModelService = brandModelService;
        }
        [Authorize(Roles = "Admin , Manager")]
        public async Task<IActionResult> Index()
        {
            List<BrandModel> brandModels = await _brandModelService.GetBrandsAsync();

            return View(brandModels);

        }
        [Authorize(Roles = "Admin , Manager")]
        public async Task<IActionResult> Details(string id)
        {
            var brandModels = await _brandModelService.GetBrandByIdAsync(id);
            if (brandModels == null) return NotFound();
            return View(brandModels);
        }
        [Authorize(Roles = "Admin ")]
        public async Task<IActionResult> Create()
        => View();
        [HttpPost]
        [Authorize(Roles = "Admin ")]
        public async Task<IActionResult> Create(CreateBrandModelDto model)
        {
            if (!ModelState.IsValid) return View(model);
            var brandsModel = await _brandModelService.GetBrandsAsync();
            bool isReplayValue = brandsModel.Any(br => br.Name.ToLower().Trim() == model.Name.ToLower().Trim());

            if (isReplayValue)
            {
                ModelState.AddModelError("Name", "Tekrarlana alan ");
            }
            await _brandModelService.Create(model);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin ")]
        public async Task<IActionResult> Update(string id)
        {
            var brandModels = await _brandModelService.GetBrandByIdAsync(id);
            if (brandModels == null) return NotFound();
            UpdateBrandModelDto updateBrandModelDto = new()
            {
                FilePath = brandModels.FilePath,
                Name = brandModels.Name,
                formFile = brandModels.formFile 
            }; return View(updateBrandModelDto);


        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(UpdateBrandModelDto model)
        {
            if (!ModelState.IsValid) return View(model);
            await _brandModelService.Update(model);
            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        [Authorize(Roles = "Admin ")]
        public async Task<IActionResult> Delete(string id)
        {
            var brandModels = await _brandModelService.GetBrandByIdAsync(id);
            if (brandModels == null) return NotFound();
            await _brandModelService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

bytez.webui/Areas/Admin/Views/BrandModel/Create.cshtml
@using bytez.business.Dto.BrandModel



@model CreateBrandModelDto

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create</h4>
            <p class="card-description">Create elements</p>
            <form class="forms-sample" asp-controller="BrandModel" asp-action="Create" asp-area="Admin" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="@Model.Name">Name</label>
                    <input asp-for="@Model.Name" type="text" class="form-control" id="exampleInputName1" placeholder="Name">
                    <span class="text-danger" asp-validation-for="@Model.Name" />
                </div>
                <div class="form-group">
                    <label asp-for="@Model.formFile">File</label>
                    <input asp-for="@Model.formFile" class="form-control" id="exampleInputName1" placeholder="Name">
                    <span class="text-danger" asp-validation-for="@Model.formFile" />
                </div>

                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <button class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidatorForm")


}

bytez.webui/Areas/Admin/Views/BrandModel/Index.cshtml
@model List<BrandModel>


<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create BrandModel</h4>
            <a class="card-description" style="display:block;  margin:20px 0" href="/admin/brand/create">
                Add BrandModel
            </a>
            <table class="table table-dark">
                <thead>
                    <tr>
                        
                        <th> Image </th>
                        <th> Name </th>
                        <th> Create Date </th>
                        <th> Update Date </th>
                        <th> Details  </th>
                        <th> Update  </th>
                        <th> Delete  </th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var brand in Model)
                        {
                            <tr>
                                <td>
                                    <img src="~/ui/assets/image/@brand.FilePath " style="width:80px; height:80px; object-fit:contain; border-radius:10px" />
                                </td>
                                <td> @brand.Name  </td>
                                
                                <td> @brand.CreatedDate</td>
                                <td> @brand.UpdatedDate</td>

                                <td> <a href="/admin/brand/details/@brand.Id">Details </a></td>
                                <td>
                                    <a href="/admin/brand/update/@brand.Id">
                                        Update
                                    </a>
                                </td>

                                <td>
                                    <form method="post" asp-controller="BrandModel" asp-action="Delete" asp-area="Admin" asp-route-id="@brand.Id">

                                         <button type="submit" class="btn btn-link"> Delete</button>
                                    </form>
                                </td>

                            </tr>
                        }
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>

bytez.webui/Areas/Admin/Views/BrandModel/Update.cshtml
@using bytez.business.Dto.BrandModel



@model UpdateBrandModelDto

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create</h4>
            <p class="card-description">Create elements</p>
            <form class="forms-sample"  enctype="multipart/form-data" method="post">
                <div class="form-group">
                    <label asp-for="@Model.Name">Name</label>
                    <input asp-for="@Model.Name" type="text" class="form-control" id="exampleInputName1" placeholder="Name">
                    <span class="text-danger" asp-validation-for="@Model.Name" />
                </div>
                <div class="form-group">
                    <img src="~/ui/assets/image/@Model.FilePath" style="width: 100px;height:100px; objet-fit:cover; border-radius:12px" />

                </div>
                <div class="form-group">
                    <label asp-for="@Model.formFile">File</label>
                    <input asp-for="@Model.formFile" class="form-control" id="exampleInputName1" placeholder="Name">
                    <span class="text-danger" asp-validation-for="@Model.formFile" />
                </div>

                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <button class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidatorForm")


}