bytez.webui/Areas/Admin/Controllers/AboutController.cs
using bytez.business.Abstract;
using bytez.business.Dto.About;
using bytez.entity.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace bytez.webui.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize(Roles = nameof(Admin))]
    public class AboutController : Controller
    {

        readonly private IAboutService _aboutService;
        public AboutController(IAboutService aboutService)
        {
            _aboutService = aboutService;
        }
        [Authorize(Roles = "Admin , Manager")]
        public async Task<IActionResult> Index()
        {
            List<About> aboutList = await _aboutService.GetAboutAsync();
            return View(aboutList);
        }
        [Authorize(Roles = "Admin , Manager")]
        public async Task<IActionResult> Details(string id)
        {
            var about = await _aboutService.GetAboutByIdAsync(id);
            if (about == null) return NotFound();
            return View(about);
        }
        [Authorize(Roles = "Admin ")]
        public async Task<IActionResult> Create()
        {
            var about =await _aboutService.GetAboutAsync();
            if(about==null) return View();
            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "Admin ")]
        public async Task<IActionResult> Create(CreateAboutDto model)
        {

            if(!ModelState.IsValid) return View(model);
                await _aboutService.Create(model);

                return RedirectToAction(nameof(Index));
            
        }
        [Authorize(Roles = "Admin ")]
        public async Task<IActionResult> Update(string id)
        {
            var about = await _aboutService.GetAboutByIdAsync(id);
            if (about == null) return NotFound();
              UpdateAboutDto updateAbout=  new UpdateAboutDto(){
                  FilePath= about.FilePath,
                  Description=about.Description,
                  file=about.file
                

              };
            return View(updateAbout);
        }

        [HttpPost]
        [Authorize(Roles = "Admin ")]
        public async Task<IActionResult> Update(UpdateAboutDto model)
        {
            if (!ModelState.IsValid) return View(model);
            await _aboutService.Update(model);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Roles = "Admin ")]
        public async Task<IActionResult> Delete(string id)
        {
            var about = await _aboutService.GetAboutByIdAsync(id);
            if (about == null) return NotFound();
            await _aboutService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

bytez.webui/Controllers/AboutController.cs
using bytez.business.Abstract;
using bytez.entity.Entities;
using Microsoft.AspNetCore.Mvc;

namespace bytez.webui.Controllers
{
    public class AboutController : Controller
    {
        readonly private IAboutService _aboutService;

        public AboutController(IAboutService aboutService)
        {
            _aboutService= aboutService;
        }
        public async Task<IActionResult> Index()
        {
            List<About> about =await _aboutService.GetAboutAsync();
            return View(about);
        }
    }
}

bytez.webui/Areas/Admin/Views/About/Create.cshtml
@using bytez.business.Dto.About
@model CreateAboutDto

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create</h4>
            <p class="card-description">Create elements</p>
            <form class="forms-sample" method="POST" asp-controller="About" asp-action="Create" asp-area="admin" enctype="multipart/form-data" >
               
                <div class="form-group">
                    <label asp-for="file">File</label>
                    <input asp-for="file" class="form-control" id="exampleInputName1" placeholder="Name">
                    <span class="text-danger" asp-validation-for="file"></span>
                  
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description"  class="form-control" id="exampleInputName1" rows='4' placeholder="Enter the Decription"></textarea>
                    <span class="text-danger" asp-validation-for="Description"></span>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <button class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidatorForm")

   
    <script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>

    <script>
      CKEDITOR.replace('Description');

    </script>
}

bytez.webui/Areas/Admin/Views/About/Index.cshtml
@model List<About>


<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create about</h4>
            <a class="card-description" style="display:block;  margin:20px 0" asp-controller="About" asp-action="Create" asp-area="Admin">
                Add about
            </a>
            <table class="table table-dark">
                <thead>
                    <tr>
                      
                        <th> Image </th>

                        <th> Create Date </th>
                        <th> Update Date </th>
                        <th> Details  </th>
                        <th> Update  </th>

                        <th> Delete  </th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var about in Model)
                        {
                            <tr>
                             

                                <td>
                                    <img src="~/ui/assets/image/@about.FilePath " style="width:80px; height:80px; object-fit:cover; border-radius:10px" />
                                </td>

                                <td> @about.CreatedDate</td>
                                <td> @about.UpdatedDate</td>

                                <td> <a href="/admin/about/@about.Id">Details </a></td>
                                <td>
                                    <a asp-controller="About" asp-action="Update" asp-area="Admin" asp-route-id="@about.Id">
                                       Update
                                    </a>
                                </td>

                                <td>
                                    <form method="post" asp-controller="About" asp-action="Delete" asp-area="Admin" asp-route-id="@about.Id">

                                        <button type="submit" class="btn btn-link"> Delete</button>
                                    </form>
                                </td>

                            </tr>
                        }
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>

bytez.webui/Areas/Admin/Views/About/Update.cshtml
@using bytez.business.Dto.About
@model UpdateAboutDto

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update</h4>
            <p class="card-description">Update elements</p>
            <form class="forms-sample" enctype="multipart/form-data" method="post">
                @if (!string.IsNullOrEmpty(Model.FilePath))
                {
                    <div class="form-group">
                        <img src="~/ui/assets/image/@Model.FilePath" style="width:100px; height:100px; object-fit:cover; border-radius:5px" />
                    </div>
                }
                <div class="form-group">
                    <label asp-for="@Model.file">File</label>
                    <input type="hidden" asp-for="@Model.FilePath" />
                    <input asp-for="@Model.file" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Description">Description</label>
                    <textarea asp-for="@Model.Description" type="text" class="form-control" id="exampleInputName1" rows='4' placeholder="Enter the Description"></textarea>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <button class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidatorForm")

    <script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Description');
    </script>
}