bytez.webui/Controllers/ContactController.cs
using bytez.business.Abstract;
using bytez.business.Dto.ContactCall;
using bytez.business.Dto.Messages;
using bytez.entity.Entities;
using bytez.webui.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace bytez.webui.Controllers
{
    public class ContactController : Controller
    {
        readonly private IContactCallService _contactCallService;
        readonly private IContactWallService _contactWallService;
        readonly private IMessageService _messageService;
        readonly private IEmailService _emailService;

        public ContactController(IContactCallService contactCallService,
                                 IContactWallService contactWallService,
                                 IMessageService messageService,
                                 IEmailService emailService)
        {
            _contactCallService = contactCallService;
            _contactWallService = contactWallService;
            _emailService = emailService;
            _messageService = messageService;
        }
        public async Task<IActionResult> Index()
        {
            var contactCall = await _contactCallService.GetContactCallAllAsync();
            var contacWall = await _contactWallService.GetContactWallAllAsync();
            var email = await _emailService.GetEmailAllAsync();
            var me = new CreateMessageDto();
            ContactIndexVM contactIndexVM = new ContactIndexVM()
            {
                ContactCall = contactCall.FirstOrDefault(),
                ContactWall = contacWall.FirstOrDefault(),
                Emails = email,
                CreateMessageDto = me

            };

            return View(contactIndexVM);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateMessageDto model)
        {
            if (!ModelState.IsValid) return View(model);
          
            await _messageService.Create(model);

            return StatusCode((int)HttpStatusCode.Created);
        }
    }
}

bytez.webui/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using bytez.webui.ViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/ui/assets/css/style.css" />
    <link rel="stylesheet" href="path/to/fontawesome/css/all.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
    <title>@ViewBag.Title</title>
</head>
<body>

    <nav>
        <div class="navbar">
            <a href="#"><img src="~/ui/assets/image/logo.png" alt="logo" /></a>

            <ul class="menu">
                <li><a href="/">Home</a></li>
                <li><a href="/store">Store</a></li>
                <li><a href="/blog">Blog</a></li>
                <li><a href="/contact">Contact</a></li>

            </ul>
        </div>

        <ul class="social-menu">
            @{
                if (!User.IsInRole("Admin") && !User.IsInRole("Manager"))
                {
                    <li><a href="#"><img src="~/ui/assets/image/Search.png" /></a></li>
                    <li><a href="#"><img src="~/ui/assets/image/cart-shopping.png" /></a></li>
                    <li class="user-item">
                        <a class="user-link"><img src="~/ui/assets/image/User.png" /></a>
                        <ul class="drapdown">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li><a class="login" href="/account/login">Login</a></li>
                                <li><a href="/account/register">Register</a></li>
                            }
                            else
                            {
                                <li>
                                    <ul class="submenu">
                                        <li>
                                            <a>@User.Identity.Name</a>
                                            <p>@((User.Identity as ClaimsIdentity)?.FindFirst(ClaimTypes.Email)?.Value)</p>
                                        </li>
                                        <li><a href="/order">Order</a></li>
                                        <li><a href="/cart">Cart</a></li>
                                        <li><a href="/wishlist">Wishlist</a></li>
                                        <li>
                                            <form asp-controller="Account" asp-action="Logout" method="post">
                                                <button type="submit">Log Out</button>
                                            </form>
                                        </li>
                                    </ul>
                                </li>
                            }
                        </ul>
                    </li>
                }
                else if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                {
                    <li><a href="/admin">Admin</a></li>
                }
            }
        </ul>

    </nav>

    <main>
        <div class="containers">

            @RenderBody()
        </div>
    </main>
    <footer>
        <section id="about">
            <div class="about-item">
                <h2 class="about-item-title">quick links</h2>
                <ul>
                    <li><a href="">Home</a></li>
                    <li><a href="">About us</a></li>
                    <li><a href="">Contact us</a></li>
                    <li><a href="">Faq</a></li>
                </ul>
            </div>
            <div class="about-item">
                <h2 class="about-item-title">important policies</h2>
                <ul>
                    <li><a href="">Privacy Policy</a></li>
                    <li><a href="">Terms of Service</a></li>
                    <li><a href="">Returns & Refunds</a></li>
                    <li><a href="">Shipping Policy</a></li>
                </ul>
            </div>
            <div class="about-item">
                <h2 class="about-item-title">let us help you</h2>
                <ul>
                    <li><a href="">Customer Support</a></li>
                    <li><a href="">Live Chat</a></li>
                    <li><a href="">Help Center</a></li>

                </ul>
            </div>
            <div class="about-item">
                <h2 class="about-item-title">connect with us</h2>
                <ul>
                    <li><a href="">facebook</a></li>
                    <li><a href="">twitter</a></li>
                    <li><a href="">instagram</a></li>

                </ul>
            </div>
            <div class="about-item">
                <h2 class="about-item-title">Subscribe for updates and exclusive offers. *</h2>
                <form class="about-form">
                    <input type="email" id="email" autocomplete="on" placeholder="Enter the Email" />
                    <button class="btn-dark">subscribe</button>
                </form>
            </div>
        </section>
    </footer>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
   
    <script src="https://kit.fontawesome.com/9df1d44044.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="	sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/ui/assets/js/fetch.js"></script>
    <script src="~/ui/assets/js/add.js"></script>
</body>
</html>

bytez.webui/Views/Shared/_createMessagePartial.cshtml
@using bytez.business.Dto.Messages
@model CreateMessageDto
<form class="form-message" method="post" asp-action="Index" asp-controller="Contact">
    <div class=" input-message">
        <input asp-for=" Name" class=" input-message" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class=" input-message">
        <input asp-for=" Email" class=" input-message" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class=" input-message">
        <input asp-for="Phone" class="input-message" />
        <span class="text-danger" asp-validation-for="Phone"></span>
    </div>
    <div class=" textarea-message">
        <textarea asp-for="MessageInfo " class=" textarea-message">
        <span class="text-danger" asp-validation-for="MessageInfo"></span>

                </textarea>
    </div>
    <button type="button">Send Message</button>
</form>

@section Scripts {
    @await Html.PartialAsync("_ValidatorForm")


}

bytez.webui/Views/Shared/_headerLogin.cshtml
@using bytez.webui.ViewModel

<style>
    .content:nth-child(3){
            display:none;
    }
</style>
@model HomeIndexVM
 @{
   
<div class="headers">
   
        @foreach (var header in Model.Headers)
        {
          
            <div class="content" >
                <h1 class="content-title">
                    @header.Title
                </h1>
                <div class="content-body">
                    @Html.Raw(header.Descripton)
                    <img src="~/ui/assets/image/@header.FilePath" alt="">
                </div>
            </div>
            
        }
  
</div>
  }

bytez.webui/Views/Shared/_headerNotLogin.cshtml
@using bytez.webui.ViewModel
@model HomeIndexVM
<style>
    .content:nth-child(4){
            display:none;
    }
</style>
 @{
   
<div class="header">
   
        @foreach (var header in Model.Headers)
        {
          
            <div class="content" >
                <h1 class="content-title">
                    @header.Title
                </h1>
                <div class="content-body">
                    @Html.Raw(header.Descripton)
                    <img src="~/ui/assets/image/@header.FilePath" alt="">
                </div>
            </div>
            
        }
  
</div>
  }